### ISSUE TITLE
Let's Update 2022 baby!

### ISSUE THREAD

**Issue by sophia-sms** [pglevy/sms-com#27]
Menu:
Take down:
Class Cards and Passion Projects

Stay:
Home - 
SMS has moved to physical location at All That & Jazz.
Private lessons at All That & Jazz. 
Lake Montclair Center
5119 Waterway Dr, Dumfries, VA 22025
(703) 730-7858
Currently private lessons are full, but group piano lesson coming soon. Sign up button for more info/update.

About Me/Contact links

Add links:
More about me and blog @SophiaLevy.com
YouTube, Facebook, Instagram, TikTok

**Comment by pglevy** [comment]
addressed by commits on 2/1/2022 up to here: 0574a68c4df6858cd29af273e897a423ee7c99d3
